# Generated by Django 5.1.7 on 2025-03-24 03:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('correo', models.EmailField(max_length=60, unique=True, verbose_name='correo')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=8)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='api_usuario_groups', related_query_name='usuario', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='api_usuario_user_permissions', related_query_name='usuario', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('tipo_documento', models.CharField(choices=[('CC', 'cedula de ciudadania'), ('CE', 'cedula de extranjeria'), ('TI', 'tarjeta de identidad'), ('RC', 'registro civil'), ('PA', 'pasaporte')], max_length=2)),
                ('numero_documento', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=40)),
                ('celular', models.CharField(max_length=13)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Manicurista',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('tipo_documento', models.CharField(choices=[('CC', 'cedula de ciudadania'), ('CE', 'cedula de extranjeria'), ('TI', 'tarjeta de identidad'), ('RC', 'registro civil'), ('PA', 'pasaporte')], max_length=2)),
                ('numero_documento', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=60)),
                ('celular', models.CharField(max_length=13)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_contratacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CitaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Descripcion', models.TextField()),
                ('Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estadocita')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('manicurista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manicurista')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoCompra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estadocompra')),
            ],
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compra')),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.insumo')),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='marca_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marca'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'NATURAL'), ('JURIDICA', 'JURIDICA')], max_length=8)),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'cedula de ciudadania')], max_length=3)),
                ('numero_documento', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('ciudad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol'),
        ),
        migrations.CreateModel(
            name='ServicioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cita_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.citaventa')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicial', models.DateField()),
                ('TotalGenerado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Local', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FechaFinal', models.DateField()),
                ('manicurista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manicurista')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('HoraEntrada', models.TimeField()),
                ('HoraSalida', models.TimeField()),
                ('Motivo', models.TextField()),
                ('manicurista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manicurista')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.insumo')),
                ('manicurista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manicurista')),
            ],
        ),
    ]
