# Generated by Django 5.1.7 on 2025-04-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameModel(
            old_name='Horario',
            new_name='Novedades',
        ),
        migrations.RemoveField(
            model_name='abastecimiento',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='abastecimiento',
            name='insumo_id',
        ),
        migrations.AddField(
            model_name='servicio',
            name='url_imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='insumoAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('abastecimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.abastecimiento')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estadoabastecimiento')),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.insumo')),
            ],
        ),
    ]
