# Generated by Django 5.1.7 on 2025-04-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estadoabastecimiento_rename_horario_novedades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumoabastecimiento',
            name='estado_id',
        ),
        migrations.RemoveField(
            model_name='insumoabastecimiento',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='insumoabastecimiento',
            name='estado',
            field=models.CharField(default='Uso', max_length=30),
        ),
        migrations.DeleteModel(
            name='EstadoAbastecimiento',
        ),
    ]
